server:
  port: 8005
mybatis:
  config-location: classpath:mybatis/mybatisConfig.xml
  type-aliases-package: com.hqj.project.entity
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml

spring:
  application:
    name: hqj-cloud-stu-hystrix
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/sql_test01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7000.com:7000/eureka,http://www.eureka7002.com:7002/eureka，http://www.eureka7001.com:7001/eureka