server:
  port: 9002
spring:
  application:
    name: hqj-cloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7000.com:7000/eureka,http://www.eureka7002.com:7002/eureka，http://www.eureka7001.com:7001/eureka
zuul:
  routes:
    hqj.serviceId: hqj-cloud-stu-hystrix
    hqj.path: /hqj-hpq/**
  ignored-services: hqj-cloud-stu-hystrix
  prefix: /hpq